name: teczaleel
description: "Advanced flutter practical assessment - junior developer"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.2.1
  dio: ^5.9.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  connectivity_plus: ^7.0.0
  equatable: ^2.0.8
  dartz: ^0.10.1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  gradient_coloured_buttons: ^0.1.0
  flutter_staggered_animations: ^1.1.1
  alert_info: ^0.0.8
  intl: ^0.20.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  mocktail: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "dev_assets/app_icon.jpg"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "dev_assets/app_icon.jpg"

flutter_native_splash:
  color: "#FFFFFF"
  image: dev_assets/logo12.png
  android_12:
    image: dev_assets/logo12.png
    color: "#FFFFFF"

flutter_assets:
  assets_path:
    - assets/images
  output_path: lib/generated
  filename: assets.dart
  field_prefix:
    from: assets
    to:
